server:
  port: 8081
  shutdown: "graceful"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345678
    hikari:
      connectionTestQuery: "SELECT 1"
      max-lifetime: 600000
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.zaxxer.hikari: DEBUG