server:
  port: 8081
  shutdown: "graceful"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ShortyDB
    username: postgres
    password: Su47berkut!
    hikari:
      connectionTestQuery: "SELECT 1"
      max-lifetime: 600000
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    com.zaxxer.hikari: DEBUG
url:
  domain:
    name: "http://localhost:8081/v1/"
aws:
  client:
    key:
      accessKey: "AKIA6GBMF34N6HJX3BHQ"
      secrectAccessKey: "A3tHyIqzrvxeqxnkLDKOYxte0/PbphcKogkMPNLp"