server:
  port: 8081
  shutdown: "graceful"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ShortyDB
    username: postgres
    password: Su47berkut!
    hikari:
      connectionTestQuery: "SELECT 1"
      max-lifetime: 600000
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: validate


logging:
  level:
    com.zaxxer.hikari: DEBUG
url:
  domain:
    name: "http://localhost:8081/v1/"
aws:
  client:
    key:
      accessKey: ${AWS_ACCESS_KEY}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}